title: How-to Hub
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

#topnav_title: Website title
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "A hub for bioinformatics focused How-to Guides"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.3.0

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/main_logo.png

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      #permalink: /:basename
      layout: "page"
      sidebar: main

  -
    scope:
      path: "genomics"
      type: "pages"
    values:
      type: genomics

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
  - elixir-toolkit-theme-plugins
