
name: Update guides

on:
  workflow_dispatch:

jobs:

  update_guides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.16'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute table conversion script
        run: python scripts/guides_table_conversion.py

      - name: Commit if updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "update guides"

      - name: Push if changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
